parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $rabbitProducerUploadImage: '@old_sound_rabbit_mq.upload_image_producer'
            $rabbitProducerImageProcessed: '@old_sound_rabbit_mq.image_processed_producer'
            $fileHandlerDirectory: '%kernel.project_dir%/../upload/files'

    Imgix\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Imgix\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
