old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        upload_image:
            connection:       default
            exchange_options: { name: 'amq.direct', type: direct }
        image_processed:
            connection:       default
            exchange_options: { name: 'amq.direct', type: direct }

    consumers:
        image_ready:
            connection:       default
            exchange_options: { name: 'amq.direct', type: direct }
            queue_options:    { name: 'image-ready-backend'}
            callback:         Imgix\Consumer\ImageProcessedConsumer
